---
abstract: 'Watch latest software releases'
author:
  - 'Steven Haryanto <stevenharyanto@gmail.com>'
build_requires:
  Module::Build: 0.3601
configure_requires:
  Module::Build: 0.3601
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300006, CPAN::Meta::Converter version 2.113640'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Software-Release-Watch
requires:
  Log::Any: 0
  Module::List: 0
  Moo: 0
  Moo::Role: 0
  Perinci::CmdLine: 0.67
  Perinci::Sub::Gen::AccessTable: 0.17
  SemVer: v0.3.0
  Software::Catalog: 0.03
  WWW::Mechanize: 0
  perl: 5.010001
resources:
  homepage: http://metacpan.org/release/Software-Release-Watch
  repository: http://github.com/sharyanto/perl-Software-Release-Watch
version: 0.01
